### ISSUE TITLE
port `FNO2d` to this repo

### ISSUE THREAD

**Issue by Lutra-Fs** [techlauncher-mlai-edge-physics/neural_net_physics_tf#4]

**Comment by kyubxy** [comment]
user story points: 8

**Comment by Track07-cda** [comment]
Issue with gradient calculation for FNO2d model. 
Planning to implement the simpler [FNO2dLite](https://github.com/techlauncher-mlai-edge-physics/neural_nets/blob/main/src/nn_modules.py#L294) for temporary work around.
